
spring:
  datasource:
    username: root
    password: password
    url: jdbc:mariadb://localhost:3306/product_db
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    # hibernate:
    #   ddlAuto: none
    show-sql: true
  kafka:
    bootstrap-servers:
    - localhost:9092
    producer:
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      autoOffsetReset: latest
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # should be set for consumer to deserialize correctly
      properties.spring.json.trusted.packages: org.rkumara.kafkademo.event